// Code generated by MockGen. DO NOT EDIT.
// Source: querier.go
//
// Generated by this command:
//
//	mockgen -source=querier.go -destination=mocks/querier_mock.go -package=repomocks
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	repository "go-ecommerce-app/internal/repository"
	reflect "reflect"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AddCartItem mocks base method.
func (m *MockQuerier) AddCartItem(ctx context.Context, arg repository.AddCartItemParams) (repository.AddCartItemRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCartItem", ctx, arg)
	ret0, _ := ret[0].(repository.AddCartItemRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCartItem indicates an expected call of AddCartItem.
func (mr *MockQuerierMockRecorder) AddCartItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCartItem", reflect.TypeOf((*MockQuerier)(nil).AddCartItem), ctx, arg)
}

// AdminCountProducts mocks base method.
func (m *MockQuerier) AdminCountProducts(ctx context.Context, arg repository.AdminCountProductsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminCountProducts", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminCountProducts indicates an expected call of AdminCountProducts.
func (mr *MockQuerierMockRecorder) AdminCountProducts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminCountProducts", reflect.TypeOf((*MockQuerier)(nil).AdminCountProducts), ctx, arg)
}

// AdminGetDistinctCategories mocks base method.
func (m *MockQuerier) AdminGetDistinctCategories(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminGetDistinctCategories", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminGetDistinctCategories indicates an expected call of AdminGetDistinctCategories.
func (mr *MockQuerierMockRecorder) AdminGetDistinctCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetDistinctCategories", reflect.TypeOf((*MockQuerier)(nil).AdminGetDistinctCategories), ctx)
}

// AdminGetProductByID mocks base method.
func (m *MockQuerier) AdminGetProductByID(ctx context.Context, id pgtype.UUID) (repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminGetProductByID", ctx, id)
	ret0, _ := ret[0].(repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminGetProductByID indicates an expected call of AdminGetProductByID.
func (mr *MockQuerierMockRecorder) AdminGetProductByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetProductByID", reflect.TypeOf((*MockQuerier)(nil).AdminGetProductByID), ctx, id)
}

// AdminGetProductBySKU mocks base method.
func (m *MockQuerier) AdminGetProductBySKU(ctx context.Context, sku string) (repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminGetProductBySKU", ctx, sku)
	ret0, _ := ret[0].(repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminGetProductBySKU indicates an expected call of AdminGetProductBySKU.
func (mr *MockQuerierMockRecorder) AdminGetProductBySKU(ctx, sku any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetProductBySKU", reflect.TypeOf((*MockQuerier)(nil).AdminGetProductBySKU), ctx, sku)
}

// AdminListProducts mocks base method.
func (m *MockQuerier) AdminListProducts(ctx context.Context, arg repository.AdminListProductsParams) ([]repository.AdminListProductsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminListProducts", ctx, arg)
	ret0, _ := ret[0].([]repository.AdminListProductsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminListProducts indicates an expected call of AdminListProducts.
func (mr *MockQuerierMockRecorder) AdminListProducts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminListProducts", reflect.TypeOf((*MockQuerier)(nil).AdminListProducts), ctx, arg)
}

// ClearCart mocks base method.
func (m *MockQuerier) ClearCart(ctx context.Context, userID pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCart", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCart indicates an expected call of ClearCart.
func (mr *MockQuerierMockRecorder) ClearCart(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCart", reflect.TypeOf((*MockQuerier)(nil).ClearCart), ctx, userID)
}

// CountProducts mocks base method.
func (m *MockQuerier) CountProducts(ctx context.Context, arg repository.CountProductsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProducts", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProducts indicates an expected call of CountProducts.
func (mr *MockQuerierMockRecorder) CountProducts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProducts", reflect.TypeOf((*MockQuerier)(nil).CountProducts), ctx, arg)
}

// CreateOrder mocks base method.
func (m *MockQuerier) CreateOrder(ctx context.Context, arg repository.CreateOrderParams) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, arg)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockQuerierMockRecorder) CreateOrder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockQuerier)(nil).CreateOrder), ctx, arg)
}

// CreateOrderItem mocks base method.
func (m *MockQuerier) CreateOrderItem(ctx context.Context, arg repository.CreateOrderItemParams) (repository.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderItem", ctx, arg)
	ret0, _ := ret[0].(repository.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrderItem indicates an expected call of CreateOrderItem.
func (mr *MockQuerierMockRecorder) CreateOrderItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderItem", reflect.TypeOf((*MockQuerier)(nil).CreateOrderItem), ctx, arg)
}

// CreateProduct mocks base method.
func (m *MockQuerier) CreateProduct(ctx context.Context, arg repository.CreateProductParams) (repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, arg)
	ret0, _ := ret[0].(repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockQuerierMockRecorder) CreateProduct(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockQuerier)(nil).CreateProduct), ctx, arg)
}

// CreateRefreshToken mocks base method.
func (m *MockQuerier) CreateRefreshToken(ctx context.Context, arg repository.CreateRefreshTokenParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockQuerierMockRecorder) CreateRefreshToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockQuerier)(nil).CreateRefreshToken), ctx, arg)
}

// CreateResetPasswordToken mocks base method.
func (m *MockQuerier) CreateResetPasswordToken(ctx context.Context, arg repository.CreateResetPasswordTokenParams) (repository.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResetPasswordToken", ctx, arg)
	ret0, _ := ret[0].(repository.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResetPasswordToken indicates an expected call of CreateResetPasswordToken.
func (mr *MockQuerierMockRecorder) CreateResetPasswordToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResetPasswordToken", reflect.TypeOf((*MockQuerier)(nil).CreateResetPasswordToken), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockQuerier) CreateUser(ctx context.Context, arg repository.CreateUserParams) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockQuerierMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockQuerier)(nil).CreateUser), ctx, arg)
}

// CreateVericationEmail mocks base method.
func (m *MockQuerier) CreateVericationEmail(ctx context.Context, arg repository.CreateVericationEmailParams) (repository.EmailVerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVericationEmail", ctx, arg)
	ret0, _ := ret[0].(repository.EmailVerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVericationEmail indicates an expected call of CreateVericationEmail.
func (mr *MockQuerierMockRecorder) CreateVericationEmail(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVericationEmail", reflect.TypeOf((*MockQuerier)(nil).CreateVericationEmail), ctx, arg)
}

// DecrementProductStock mocks base method.
func (m *MockQuerier) DecrementProductStock(ctx context.Context, arg repository.DecrementProductStockParams) (repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementProductStock", ctx, arg)
	ret0, _ := ret[0].(repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementProductStock indicates an expected call of DecrementProductStock.
func (mr *MockQuerierMockRecorder) DecrementProductStock(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementProductStock", reflect.TypeOf((*MockQuerier)(nil).DecrementProductStock), ctx, arg)
}

// DeleteCartItem mocks base method.
func (m *MockQuerier) DeleteCartItem(ctx context.Context, arg repository.DeleteCartItemParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCartItem", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCartItem indicates an expected call of DeleteCartItem.
func (mr *MockQuerierMockRecorder) DeleteCartItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartItem", reflect.TypeOf((*MockQuerier)(nil).DeleteCartItem), ctx, arg)
}

// DeleteEmailVerificationByTokenHash mocks base method.
func (m *MockQuerier) DeleteEmailVerificationByTokenHash(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmailVerificationByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmailVerificationByTokenHash indicates an expected call of DeleteEmailVerificationByTokenHash.
func (mr *MockQuerierMockRecorder) DeleteEmailVerificationByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmailVerificationByTokenHash", reflect.TypeOf((*MockQuerier)(nil).DeleteEmailVerificationByTokenHash), ctx, tokenHash)
}

// DeletePasswordTokenByTokenHash mocks base method.
func (m *MockQuerier) DeletePasswordTokenByTokenHash(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePasswordTokenByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePasswordTokenByTokenHash indicates an expected call of DeletePasswordTokenByTokenHash.
func (mr *MockQuerierMockRecorder) DeletePasswordTokenByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePasswordTokenByTokenHash", reflect.TypeOf((*MockQuerier)(nil).DeletePasswordTokenByTokenHash), ctx, tokenHash)
}

// GetDistinctCategories mocks base method.
func (m *MockQuerier) GetDistinctCategories(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctCategories", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctCategories indicates an expected call of GetDistinctCategories.
func (mr *MockQuerierMockRecorder) GetDistinctCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctCategories", reflect.TypeOf((*MockQuerier)(nil).GetDistinctCategories), ctx)
}

// GetEmailVerificationByTokenHash mocks base method.
func (m *MockQuerier) GetEmailVerificationByTokenHash(ctx context.Context, tokenHash string) (repository.EmailVerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailVerificationByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(repository.EmailVerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailVerificationByTokenHash indicates an expected call of GetEmailVerificationByTokenHash.
func (mr *MockQuerierMockRecorder) GetEmailVerificationByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailVerificationByTokenHash", reflect.TypeOf((*MockQuerier)(nil).GetEmailVerificationByTokenHash), ctx, tokenHash)
}

// GetOrderByID mocks base method.
func (m *MockQuerier) GetOrderByID(ctx context.Context, id pgtype.UUID) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", ctx, id)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockQuerierMockRecorder) GetOrderByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockQuerier)(nil).GetOrderByID), ctx, id)
}

// GetOrderByMidtransID mocks base method.
func (m *MockQuerier) GetOrderByMidtransID(ctx context.Context, midtransOrderID pgtype.Text) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByMidtransID", ctx, midtransOrderID)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByMidtransID indicates an expected call of GetOrderByMidtransID.
func (mr *MockQuerierMockRecorder) GetOrderByMidtransID(ctx, midtransOrderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByMidtransID", reflect.TypeOf((*MockQuerier)(nil).GetOrderByMidtransID), ctx, midtransOrderID)
}

// GetProductByID mocks base method.
func (m *MockQuerier) GetProductByID(ctx context.Context, id pgtype.UUID) (repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", ctx, id)
	ret0, _ := ret[0].(repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockQuerierMockRecorder) GetProductByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockQuerier)(nil).GetProductByID), ctx, id)
}

// GetRefreshToken mocks base method.
func (m *MockQuerier) GetRefreshToken(ctx context.Context, tokenHash string) (repository.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", ctx, tokenHash)
	ret0, _ := ret[0].(repository.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockQuerierMockRecorder) GetRefreshToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockQuerier)(nil).GetRefreshToken), ctx, tokenHash)
}

// GetRefreshTokenAnyStatus mocks base method.
func (m *MockQuerier) GetRefreshTokenAnyStatus(ctx context.Context, tokenHash string) (repository.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenAnyStatus", ctx, tokenHash)
	ret0, _ := ret[0].(repository.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenAnyStatus indicates an expected call of GetRefreshTokenAnyStatus.
func (mr *MockQuerierMockRecorder) GetRefreshTokenAnyStatus(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenAnyStatus", reflect.TypeOf((*MockQuerier)(nil).GetRefreshTokenAnyStatus), ctx, tokenHash)
}

// GetResetPasswordTokenByTokenHash mocks base method.
func (m *MockQuerier) GetResetPasswordTokenByTokenHash(ctx context.Context, tokenHash string) (repository.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResetPasswordTokenByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(repository.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResetPasswordTokenByTokenHash indicates an expected call of GetResetPasswordTokenByTokenHash.
func (mr *MockQuerierMockRecorder) GetResetPasswordTokenByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResetPasswordTokenByTokenHash", reflect.TypeOf((*MockQuerier)(nil).GetResetPasswordTokenByTokenHash), ctx, tokenHash)
}

// GetUserByEmail mocks base method.
func (m *MockQuerier) GetUserByEmail(ctx context.Context, email string) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockQuerierMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockQuerier)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockQuerier) GetUserByID(ctx context.Context, id pgtype.UUID) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockQuerierMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockQuerier)(nil).GetUserByID), ctx, id)
}

// IncrementProductStock mocks base method.
func (m *MockQuerier) IncrementProductStock(ctx context.Context, arg repository.IncrementProductStockParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementProductStock", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementProductStock indicates an expected call of IncrementProductStock.
func (mr *MockQuerierMockRecorder) IncrementProductStock(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementProductStock", reflect.TypeOf((*MockQuerier)(nil).IncrementProductStock), ctx, arg)
}

// ListCartItems mocks base method.
func (m *MockQuerier) ListCartItems(ctx context.Context, userID pgtype.UUID) ([]repository.ListCartItemsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCartItems", ctx, userID)
	ret0, _ := ret[0].([]repository.ListCartItemsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCartItems indicates an expected call of ListCartItems.
func (mr *MockQuerierMockRecorder) ListCartItems(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCartItems", reflect.TypeOf((*MockQuerier)(nil).ListCartItems), ctx, userID)
}

// ListExpiredPendingOrders mocks base method.
func (m *MockQuerier) ListExpiredPendingOrders(ctx context.Context, createdAt pgtype.Timestamptz) ([]repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpiredPendingOrders", ctx, createdAt)
	ret0, _ := ret[0].([]repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpiredPendingOrders indicates an expected call of ListExpiredPendingOrders.
func (mr *MockQuerierMockRecorder) ListExpiredPendingOrders(ctx, createdAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpiredPendingOrders", reflect.TypeOf((*MockQuerier)(nil).ListExpiredPendingOrders), ctx, createdAt)
}

// ListOrderItemsByOrder mocks base method.
func (m *MockQuerier) ListOrderItemsByOrder(ctx context.Context, orderID pgtype.UUID) ([]repository.OrderItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrderItemsByOrder", ctx, orderID)
	ret0, _ := ret[0].([]repository.OrderItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrderItemsByOrder indicates an expected call of ListOrderItemsByOrder.
func (mr *MockQuerierMockRecorder) ListOrderItemsByOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrderItemsByOrder", reflect.TypeOf((*MockQuerier)(nil).ListOrderItemsByOrder), ctx, orderID)
}

// ListOrdersByUser mocks base method.
func (m *MockQuerier) ListOrdersByUser(ctx context.Context, userID pgtype.UUID) ([]repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrdersByUser", ctx, userID)
	ret0, _ := ret[0].([]repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrdersByUser indicates an expected call of ListOrdersByUser.
func (mr *MockQuerierMockRecorder) ListOrdersByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrdersByUser", reflect.TypeOf((*MockQuerier)(nil).ListOrdersByUser), ctx, userID)
}

// ListProducts mocks base method.
func (m *MockQuerier) ListProducts(ctx context.Context, arg repository.ListProductsParams) ([]repository.ListProductsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, arg)
	ret0, _ := ret[0].([]repository.ListProductsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockQuerierMockRecorder) ListProducts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockQuerier)(nil).ListProducts), ctx, arg)
}

// RevokeRefreshToken mocks base method.
func (m *MockQuerier) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshToken", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshToken indicates an expected call of RevokeRefreshToken.
func (mr *MockQuerierMockRecorder) RevokeRefreshToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshToken", reflect.TypeOf((*MockQuerier)(nil).RevokeRefreshToken), ctx, tokenHash)
}

// RevokeRefreshTokenByUserID mocks base method.
func (m *MockQuerier) RevokeRefreshTokenByUserID(ctx context.Context, userID pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshTokenByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshTokenByUserID indicates an expected call of RevokeRefreshTokenByUserID.
func (mr *MockQuerierMockRecorder) RevokeRefreshTokenByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshTokenByUserID", reflect.TypeOf((*MockQuerier)(nil).RevokeRefreshTokenByUserID), ctx, userID)
}

// SetOrderPaymentInfo mocks base method.
func (m *MockQuerier) SetOrderPaymentInfo(ctx context.Context, arg repository.SetOrderPaymentInfoParams) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOrderPaymentInfo", ctx, arg)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetOrderPaymentInfo indicates an expected call of SetOrderPaymentInfo.
func (mr *MockQuerierMockRecorder) SetOrderPaymentInfo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOrderPaymentInfo", reflect.TypeOf((*MockQuerier)(nil).SetOrderPaymentInfo), ctx, arg)
}

// SetUserVerified mocks base method.
func (m *MockQuerier) SetUserVerified(ctx context.Context, id pgtype.UUID) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserVerified", ctx, id)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserVerified indicates an expected call of SetUserVerified.
func (mr *MockQuerierMockRecorder) SetUserVerified(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserVerified", reflect.TypeOf((*MockQuerier)(nil).SetUserVerified), ctx, id)
}

// SoftDeleteProduct mocks base method.
func (m *MockQuerier) SoftDeleteProduct(ctx context.Context, id pgtype.UUID) (repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteProduct", ctx, id)
	ret0, _ := ret[0].(repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteProduct indicates an expected call of SoftDeleteProduct.
func (mr *MockQuerierMockRecorder) SoftDeleteProduct(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteProduct", reflect.TypeOf((*MockQuerier)(nil).SoftDeleteProduct), ctx, id)
}

// UpdateCartItemQuantity mocks base method.
func (m *MockQuerier) UpdateCartItemQuantity(ctx context.Context, arg repository.UpdateCartItemQuantityParams) (repository.UpdateCartItemQuantityRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartItemQuantity", ctx, arg)
	ret0, _ := ret[0].(repository.UpdateCartItemQuantityRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCartItemQuantity indicates an expected call of UpdateCartItemQuantity.
func (mr *MockQuerierMockRecorder) UpdateCartItemQuantity(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartItemQuantity", reflect.TypeOf((*MockQuerier)(nil).UpdateCartItemQuantity), ctx, arg)
}

// UpdateOrderStatus mocks base method.
func (m *MockQuerier) UpdateOrderStatus(ctx context.Context, arg repository.UpdateOrderStatusParams) (repository.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrderStatus", ctx, arg)
	ret0, _ := ret[0].(repository.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatus indicates an expected call of UpdateOrderStatus.
func (mr *MockQuerierMockRecorder) UpdateOrderStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateOrderStatus), ctx, arg)
}

// UpdatePasswordUser mocks base method.
func (m *MockQuerier) UpdatePasswordUser(ctx context.Context, arg repository.UpdatePasswordUserParams) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordUser", ctx, arg)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePasswordUser indicates an expected call of UpdatePasswordUser.
func (mr *MockQuerierMockRecorder) UpdatePasswordUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordUser", reflect.TypeOf((*MockQuerier)(nil).UpdatePasswordUser), ctx, arg)
}

// UpdateProduct mocks base method.
func (m *MockQuerier) UpdateProduct(ctx context.Context, arg repository.UpdateProductParams) (repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, arg)
	ret0, _ := ret[0].(repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockQuerierMockRecorder) UpdateProduct(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockQuerier)(nil).UpdateProduct), ctx, arg)
}

// UpdateUserRole mocks base method.
func (m *MockQuerier) UpdateUserRole(ctx context.Context, arg repository.UpdateUserRoleParams) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRole", ctx, arg)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserRole indicates an expected call of UpdateUserRole.
func (mr *MockQuerierMockRecorder) UpdateUserRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRole", reflect.TypeOf((*MockQuerier)(nil).UpdateUserRole), ctx, arg)
}
