// Code generated by MockGen. DO NOT EDIT.
// Source: querier.go
//
// Generated by this command:
//
//	mockgen -source=querier.go -destination=mocks/querier_mock.go -package=repomocks
//

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	repository "go-ecommerce-app/internal/repository"
	reflect "reflect"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AdminCountProducts mocks base method.
func (m *MockQuerier) AdminCountProducts(ctx context.Context, arg repository.AdminCountProductsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminCountProducts", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminCountProducts indicates an expected call of AdminCountProducts.
func (mr *MockQuerierMockRecorder) AdminCountProducts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminCountProducts", reflect.TypeOf((*MockQuerier)(nil).AdminCountProducts), ctx, arg)
}

// AdminGetDistinctCategories mocks base method.
func (m *MockQuerier) AdminGetDistinctCategories(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminGetDistinctCategories", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminGetDistinctCategories indicates an expected call of AdminGetDistinctCategories.
func (mr *MockQuerierMockRecorder) AdminGetDistinctCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetDistinctCategories", reflect.TypeOf((*MockQuerier)(nil).AdminGetDistinctCategories), ctx)
}

// AdminGetProductByID mocks base method.
func (m *MockQuerier) AdminGetProductByID(ctx context.Context, id pgtype.UUID) (repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminGetProductByID", ctx, id)
	ret0, _ := ret[0].(repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminGetProductByID indicates an expected call of AdminGetProductByID.
func (mr *MockQuerierMockRecorder) AdminGetProductByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGetProductByID", reflect.TypeOf((*MockQuerier)(nil).AdminGetProductByID), ctx, id)
}

// AdminListProducts mocks base method.
func (m *MockQuerier) AdminListProducts(ctx context.Context, arg repository.AdminListProductsParams) ([]repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminListProducts", ctx, arg)
	ret0, _ := ret[0].([]repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminListProducts indicates an expected call of AdminListProducts.
func (mr *MockQuerierMockRecorder) AdminListProducts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminListProducts", reflect.TypeOf((*MockQuerier)(nil).AdminListProducts), ctx, arg)
}

// CountProducts mocks base method.
func (m *MockQuerier) CountProducts(ctx context.Context, arg repository.CountProductsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProducts", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProducts indicates an expected call of CountProducts.
func (mr *MockQuerierMockRecorder) CountProducts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProducts", reflect.TypeOf((*MockQuerier)(nil).CountProducts), ctx, arg)
}

// CreateProduct mocks base method.
func (m *MockQuerier) CreateProduct(ctx context.Context, arg repository.CreateProductParams) (repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, arg)
	ret0, _ := ret[0].(repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockQuerierMockRecorder) CreateProduct(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockQuerier)(nil).CreateProduct), ctx, arg)
}

// CreateRefreshToken mocks base method.
func (m *MockQuerier) CreateRefreshToken(ctx context.Context, arg repository.CreateRefreshTokenParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockQuerierMockRecorder) CreateRefreshToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockQuerier)(nil).CreateRefreshToken), ctx, arg)
}

// CreateResetPasswordToken mocks base method.
func (m *MockQuerier) CreateResetPasswordToken(ctx context.Context, arg repository.CreateResetPasswordTokenParams) (repository.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResetPasswordToken", ctx, arg)
	ret0, _ := ret[0].(repository.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResetPasswordToken indicates an expected call of CreateResetPasswordToken.
func (mr *MockQuerierMockRecorder) CreateResetPasswordToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResetPasswordToken", reflect.TypeOf((*MockQuerier)(nil).CreateResetPasswordToken), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockQuerier) CreateUser(ctx context.Context, arg repository.CreateUserParams) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockQuerierMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockQuerier)(nil).CreateUser), ctx, arg)
}

// CreateVericationEmail mocks base method.
func (m *MockQuerier) CreateVericationEmail(ctx context.Context, arg repository.CreateVericationEmailParams) (repository.EmailVerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVericationEmail", ctx, arg)
	ret0, _ := ret[0].(repository.EmailVerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVericationEmail indicates an expected call of CreateVericationEmail.
func (mr *MockQuerierMockRecorder) CreateVericationEmail(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVericationEmail", reflect.TypeOf((*MockQuerier)(nil).CreateVericationEmail), ctx, arg)
}

// DeleteEmailVerificationByTokenHash mocks base method.
func (m *MockQuerier) DeleteEmailVerificationByTokenHash(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmailVerificationByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmailVerificationByTokenHash indicates an expected call of DeleteEmailVerificationByTokenHash.
func (mr *MockQuerierMockRecorder) DeleteEmailVerificationByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmailVerificationByTokenHash", reflect.TypeOf((*MockQuerier)(nil).DeleteEmailVerificationByTokenHash), ctx, tokenHash)
}

// DeletePasswordTokenByTokenHash mocks base method.
func (m *MockQuerier) DeletePasswordTokenByTokenHash(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePasswordTokenByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePasswordTokenByTokenHash indicates an expected call of DeletePasswordTokenByTokenHash.
func (mr *MockQuerierMockRecorder) DeletePasswordTokenByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePasswordTokenByTokenHash", reflect.TypeOf((*MockQuerier)(nil).DeletePasswordTokenByTokenHash), ctx, tokenHash)
}

// GetDistinctCategories mocks base method.
func (m *MockQuerier) GetDistinctCategories(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDistinctCategories", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDistinctCategories indicates an expected call of GetDistinctCategories.
func (mr *MockQuerierMockRecorder) GetDistinctCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDistinctCategories", reflect.TypeOf((*MockQuerier)(nil).GetDistinctCategories), ctx)
}

// GetEmailVerificationByTokenHash mocks base method.
func (m *MockQuerier) GetEmailVerificationByTokenHash(ctx context.Context, tokenHash string) (repository.EmailVerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailVerificationByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(repository.EmailVerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailVerificationByTokenHash indicates an expected call of GetEmailVerificationByTokenHash.
func (mr *MockQuerierMockRecorder) GetEmailVerificationByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailVerificationByTokenHash", reflect.TypeOf((*MockQuerier)(nil).GetEmailVerificationByTokenHash), ctx, tokenHash)
}

// GetProductByID mocks base method.
func (m *MockQuerier) GetProductByID(ctx context.Context, id pgtype.UUID) (repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", ctx, id)
	ret0, _ := ret[0].(repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockQuerierMockRecorder) GetProductByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockQuerier)(nil).GetProductByID), ctx, id)
}

// GetRefreshToken mocks base method.
func (m *MockQuerier) GetRefreshToken(ctx context.Context, tokenHash string) (repository.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken", ctx, tokenHash)
	ret0, _ := ret[0].(repository.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockQuerierMockRecorder) GetRefreshToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockQuerier)(nil).GetRefreshToken), ctx, tokenHash)
}

// GetRefreshTokenAnyStatus mocks base method.
func (m *MockQuerier) GetRefreshTokenAnyStatus(ctx context.Context, tokenHash string) (repository.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenAnyStatus", ctx, tokenHash)
	ret0, _ := ret[0].(repository.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenAnyStatus indicates an expected call of GetRefreshTokenAnyStatus.
func (mr *MockQuerierMockRecorder) GetRefreshTokenAnyStatus(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenAnyStatus", reflect.TypeOf((*MockQuerier)(nil).GetRefreshTokenAnyStatus), ctx, tokenHash)
}

// GetResetPasswordTokenByTokenHash mocks base method.
func (m *MockQuerier) GetResetPasswordTokenByTokenHash(ctx context.Context, tokenHash string) (repository.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResetPasswordTokenByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(repository.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResetPasswordTokenByTokenHash indicates an expected call of GetResetPasswordTokenByTokenHash.
func (mr *MockQuerierMockRecorder) GetResetPasswordTokenByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResetPasswordTokenByTokenHash", reflect.TypeOf((*MockQuerier)(nil).GetResetPasswordTokenByTokenHash), ctx, tokenHash)
}

// GetUserByEmail mocks base method.
func (m *MockQuerier) GetUserByEmail(ctx context.Context, email string) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockQuerierMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockQuerier)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockQuerier) GetUserByID(ctx context.Context, id pgtype.UUID) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockQuerierMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockQuerier)(nil).GetUserByID), ctx, id)
}

// ListProducts mocks base method.
func (m *MockQuerier) ListProducts(ctx context.Context, arg repository.ListProductsParams) ([]repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, arg)
	ret0, _ := ret[0].([]repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockQuerierMockRecorder) ListProducts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockQuerier)(nil).ListProducts), ctx, arg)
}

// RevokeRefreshToken mocks base method.
func (m *MockQuerier) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshToken", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshToken indicates an expected call of RevokeRefreshToken.
func (mr *MockQuerierMockRecorder) RevokeRefreshToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshToken", reflect.TypeOf((*MockQuerier)(nil).RevokeRefreshToken), ctx, tokenHash)
}

// RevokeRefreshTokenByUserID mocks base method.
func (m *MockQuerier) RevokeRefreshTokenByUserID(ctx context.Context, userID pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRefreshTokenByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRefreshTokenByUserID indicates an expected call of RevokeRefreshTokenByUserID.
func (mr *MockQuerierMockRecorder) RevokeRefreshTokenByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRefreshTokenByUserID", reflect.TypeOf((*MockQuerier)(nil).RevokeRefreshTokenByUserID), ctx, userID)
}

// SetUserVerified mocks base method.
func (m *MockQuerier) SetUserVerified(ctx context.Context, id pgtype.UUID) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserVerified", ctx, id)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserVerified indicates an expected call of SetUserVerified.
func (mr *MockQuerierMockRecorder) SetUserVerified(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserVerified", reflect.TypeOf((*MockQuerier)(nil).SetUserVerified), ctx, id)
}

// SoftDeleteProduct mocks base method.
func (m *MockQuerier) SoftDeleteProduct(ctx context.Context, id pgtype.UUID) (repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteProduct", ctx, id)
	ret0, _ := ret[0].(repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteProduct indicates an expected call of SoftDeleteProduct.
func (mr *MockQuerierMockRecorder) SoftDeleteProduct(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteProduct", reflect.TypeOf((*MockQuerier)(nil).SoftDeleteProduct), ctx, id)
}

// UpdatePasswordUser mocks base method.
func (m *MockQuerier) UpdatePasswordUser(ctx context.Context, arg repository.UpdatePasswordUserParams) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordUser", ctx, arg)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePasswordUser indicates an expected call of UpdatePasswordUser.
func (mr *MockQuerierMockRecorder) UpdatePasswordUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordUser", reflect.TypeOf((*MockQuerier)(nil).UpdatePasswordUser), ctx, arg)
}

// UpdateProduct mocks base method.
func (m *MockQuerier) UpdateProduct(ctx context.Context, arg repository.UpdateProductParams) (repository.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, arg)
	ret0, _ := ret[0].(repository.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockQuerierMockRecorder) UpdateProduct(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockQuerier)(nil).UpdateProduct), ctx, arg)
}

// UpdateUserRole mocks base method.
func (m *MockQuerier) UpdateUserRole(ctx context.Context, arg repository.UpdateUserRoleParams) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRole", ctx, arg)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserRole indicates an expected call of UpdateUserRole.
func (mr *MockQuerierMockRecorder) UpdateUserRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRole", reflect.TypeOf((*MockQuerier)(nil).UpdateUserRole), ctx, arg)
}
