// Code generated by MockGen. DO NOT EDIT.
// Source: payment.go
//
// Generated by this command:
//
//	mockgen -source=payment.go -destination=mocks/payment/payment_mock.go -package=paymentmocks
//

// Package paymentmocks is a generated GoMock package.
package paymentmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentClient is a mock of PaymentClient interface.
type MockPaymentClient struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentClientMockRecorder
	isgomock struct{}
}

// MockPaymentClientMockRecorder is the mock recorder for MockPaymentClient.
type MockPaymentClientMockRecorder struct {
	mock *MockPaymentClient
}

// NewMockPaymentClient creates a new mock instance.
func NewMockPaymentClient(ctrl *gomock.Controller) *MockPaymentClient {
	mock := &MockPaymentClient{ctrl: ctrl}
	mock.recorder = &MockPaymentClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentClient) EXPECT() *MockPaymentClientMockRecorder {
	return m.recorder
}

// CreateSnapTransaction mocks base method.
func (m *MockPaymentClient) CreateSnapTransaction(ctx context.Context, orderID string, grossAmount int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapTransaction", ctx, orderID, grossAmount)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSnapTransaction indicates an expected call of CreateSnapTransaction.
func (mr *MockPaymentClientMockRecorder) CreateSnapTransaction(ctx, orderID, grossAmount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapTransaction", reflect.TypeOf((*MockPaymentClient)(nil).CreateSnapTransaction), ctx, orderID, grossAmount)
}

// VerifySignature mocks base method.
func (m *MockPaymentClient) VerifySignature(orderID, statusCode, grossAmount, signatureKey string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySignature", orderID, statusCode, grossAmount, signatureKey)
	ret0, _ := ret[0].(bool)
	return ret0
}

// VerifySignature indicates an expected call of VerifySignature.
func (mr *MockPaymentClientMockRecorder) VerifySignature(orderID, statusCode, grossAmount, signatureKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySignature", reflect.TypeOf((*MockPaymentClient)(nil).VerifySignature), orderID, statusCode, grossAmount, signatureKey)
}
