// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart_items.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCartItem = `-- name: AddCartItem :one
INSERT INTO cart_items (user_id, product_id, quantity)
SELECT $1, $2, $3
WHERE $3 <= (SELECT stock FROM products WHERE id = $2)
ON CONFLICT (user_id, product_id)
DO UPDATE SET quantity = cart_items.quantity + EXCLUDED.quantity,
              updated_at = now()
WHERE cart_items.quantity + EXCLUDED.quantity <= (SELECT stock FROM products WHERE id = EXCLUDED.product_id)
RETURNING id, user_id, product_id, quantity, created_at, updated_at
`

type AddCartItemParams struct {
	UserID    pgtype.UUID
	ProductID pgtype.UUID
	Quantity  int32
}

// Validates against the live product stock inside the same statement so a
// concurrent add for the same user/product can't push quantity over stock
// (the ON CONFLICT DO UPDATE branch takes the row lock before its WHERE
// check runs, so no external check-then-write step is needed).
func (q *Queries) AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, addCartItem, arg.UserID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE user_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearCart, userID)
	return err
}

const deleteCartItem = `-- name: DeleteCartItem :execrows
DELETE FROM cart_items
WHERE user_id = $1
    AND product_id = $2
`

type DeleteCartItemParams struct {
	UserID    pgtype.UUID
	ProductID pgtype.UUID
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCartItem, arg.UserID, arg.ProductID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCartItems = `-- name: ListCartItems :many
SELECT
    ci.product_id,
    ci.quantity,
    p.name,
    p.price,
    p.image_url,
    p.is_active,
    p.stock,
    (ci.quantity * p.price)::numeric AS subtotal
FROM cart_items ci
JOIN products p ON p.id = ci.product_id
WHERE ci.user_id = $1
ORDER BY ci.created_at DESC
`

type ListCartItemsRow struct {
	ProductID pgtype.UUID
	Quantity  int32
	Name      string
	Price     pgtype.Numeric
	ImageUrl  pgtype.Text
	IsActive  bool
	Stock     int32
	Subtotal  pgtype.Numeric
}

func (q *Queries) ListCartItems(ctx context.Context, userID pgtype.UUID) ([]ListCartItemsRow, error) {
	rows, err := q.db.Query(ctx, listCartItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCartItemsRow
	for rows.Next() {
		var i ListCartItemsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Quantity,
			&i.Name,
			&i.Price,
			&i.ImageUrl,
			&i.IsActive,
			&i.Stock,
			&i.Subtotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items
SET quantity = $1,
    updated_at = now()
WHERE user_id = $2
    AND product_id = $3
RETURNING id, user_id, product_id, quantity, created_at, updated_at
`

type UpdateCartItemQuantityParams struct {
	Quantity  int32
	UserID    pgtype.UUID
	ProductID pgtype.UUID
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.Quantity, arg.UserID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
