// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart_items.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCartItem = `-- name: AddCartItem :one
WITH target_product AS (
    SELECT products.id, products.name, products.price, products.image_url, products.stock
    FROM products
    WHERE products.id = $1 AND products.is_active = true
),
upsert AS (
    INSERT INTO cart_items (user_id, product_id, quantity)
    SELECT $2, $1, $3
    WHERE $3::int <= (SELECT stock FROM target_product)
    ON CONFLICT (user_id, product_id)
    DO UPDATE SET quantity = cart_items.quantity + EXCLUDED.quantity,
                  updated_at = now()
    WHERE cart_items.quantity + EXCLUDED.quantity <= (SELECT stock FROM target_product)
    RETURNING quantity
)
SELECT
    tp.id AS product_id,
    tp.name,
    tp.price,
    tp.image_url,
    u.quantity
FROM target_product tp
LEFT JOIN upsert u ON true
`

type AddCartItemParams struct {
	ProductID pgtype.UUID
	UserID    pgtype.UUID
	Quantity  int32
}

type AddCartItemRow struct {
	ProductID pgtype.UUID
	Name      string
	Price     pgtype.Numeric
	ImageUrl  pgtype.Text
	Quantity  pgtype.Int4
}

// Combines the product lookup (is_active/name/price/image for the response)
// with the stock-guarded upsert in one round trip instead of two. Zero rows
// back means the product doesn't exist or is inactive; a row with
// quantity = NULL means the product exists but the upsert's stock guard
// rejected the write (see AddCartItemParams.Quantity vs target_product.stock).
func (q *Queries) AddCartItem(ctx context.Context, arg AddCartItemParams) (AddCartItemRow, error) {
	row := q.db.QueryRow(ctx, addCartItem, arg.ProductID, arg.UserID, arg.Quantity)
	var i AddCartItemRow
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Price,
		&i.ImageUrl,
		&i.Quantity,
	)
	return i, err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items
WHERE user_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearCart, userID)
	return err
}

const deleteCartItem = `-- name: DeleteCartItem :execrows
DELETE FROM cart_items
WHERE user_id = $1
    AND product_id = $2
`

type DeleteCartItemParams struct {
	UserID    pgtype.UUID
	ProductID pgtype.UUID
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCartItem, arg.UserID, arg.ProductID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCartItems = `-- name: ListCartItems :many
SELECT
    ci.product_id,
    ci.quantity,
    p.name,
    p.price,
    p.image_url,
    p.is_active,
    p.stock,
    (ci.quantity * p.price)::numeric AS subtotal
FROM cart_items ci
JOIN products p ON p.id = ci.product_id
WHERE ci.user_id = $1
ORDER BY ci.created_at DESC
`

type ListCartItemsRow struct {
	ProductID pgtype.UUID
	Quantity  int32
	Name      string
	Price     pgtype.Numeric
	ImageUrl  pgtype.Text
	IsActive  bool
	Stock     int32
	Subtotal  pgtype.Numeric
}

func (q *Queries) ListCartItems(ctx context.Context, userID pgtype.UUID) ([]ListCartItemsRow, error) {
	rows, err := q.db.Query(ctx, listCartItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCartItemsRow
	for rows.Next() {
		var i ListCartItemsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Quantity,
			&i.Name,
			&i.Price,
			&i.ImageUrl,
			&i.IsActive,
			&i.Stock,
			&i.Subtotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
WITH target_product AS (
    SELECT products.id, products.name, products.price, products.image_url, products.stock
    FROM products
    WHERE products.id = $1 AND products.is_active = true
),
existing_item AS (
    SELECT 1 AS found FROM cart_items
    WHERE cart_items.user_id = $2 AND cart_items.product_id = $1
),
updated AS (
    UPDATE cart_items
    SET quantity = $3,
        updated_at = now()
    WHERE user_id = $2
        AND product_id = $1
        AND $3::int <= (SELECT stock FROM target_product)
    RETURNING quantity
)
SELECT
    tp.id AS product_id,
    tp.name,
    tp.price,
    tp.image_url,
    EXISTS (SELECT 1 FROM existing_item) AS item_exists,
    u.quantity
FROM target_product tp
LEFT JOIN updated u ON true
`

type UpdateCartItemQuantityParams struct {
	ProductID pgtype.UUID
	UserID    pgtype.UUID
	Quantity  int32
}

type UpdateCartItemQuantityRow struct {
	ProductID  pgtype.UUID
	Name       string
	Price      pgtype.Numeric
	ImageUrl   pgtype.Text
	ItemExists bool
	Quantity   pgtype.Int4
}

// Same idea as AddCartItem: one round trip instead of a product lookup plus
// the update. Zero rows means the product doesn't exist or is inactive;
// item_exists = false means there's no cart_items row for this user/product
// yet; quantity = NULL (with item_exists = true) means the new quantity
// exceeds stock, so the guarded UPDATE didn't apply.
func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (UpdateCartItemQuantityRow, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.ProductID, arg.UserID, arg.Quantity)
	var i UpdateCartItemQuantityRow
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.Price,
		&i.ImageUrl,
		&i.ItemExists,
		&i.Quantity,
	)
	return i, err
}
