// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification_tokens.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVericationEmail = `-- name: CreateVericationEmail :one
INSERT INTO email_verification_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at, updated_at
`

type CreateVericationEmailParams struct {
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateVericationEmail(ctx context.Context, arg CreateVericationEmailParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createVericationEmail, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmailVerificationByTokenHash = `-- name: DeleteEmailVerificationByTokenHash :exec
DELETE FROM email_verification_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteEmailVerificationByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationByTokenHash, tokenHash)
	return err
}

const getEmailVerificationByTokenHash = `-- name: GetEmailVerificationByTokenHash :one
SELECT id, user_id, token_hash, expires_at, created_at, updated_at FROM email_verification_tokens
WHERE token_hash = $1 AND expires_at > now()
`

func (q *Queries) GetEmailVerificationByTokenHash(ctx context.Context, tokenHash string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationByTokenHash, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
