// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CartItem struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ProductID pgtype.UUID
	Quantity  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type EmailVerificationToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Order struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Status          string
	TotalAmount     pgtype.Numeric
	MidtransOrderID pgtype.Text
	SnapToken       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	PaidAt          pgtype.Timestamptz
}

type OrderItem struct {
	ID          pgtype.UUID
	OrderID     pgtype.UUID
	ProductID   pgtype.UUID
	ProductName string
	Price       pgtype.Numeric
	Quantity    int32
	Subtotal    pgtype.Numeric
	CreatedAt   pgtype.Timestamptz
}

type PasswordResetToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Product struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	Price       pgtype.Numeric
	Stock       int32
	Sku         string
	Category    string
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ImageUrl    pgtype.Text
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	FullName        string
	Email           string
	PasswordHash    string
	Role            string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	EmailVerifiedAt pgtype.Timestamptz
}
