// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, status, total_amount)
VALUES ($1, $2, $3)
RETURNING id, user_id, status, total_amount, midtrans_order_id, snap_token, created_at, updated_at, paid_at
`

type CreateOrderParams struct {
	UserID      pgtype.UUID
	Status      string
	TotalAmount pgtype.Numeric
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.Status, arg.TotalAmount)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.MidtransOrderID,
		&i.SnapToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, status, total_amount, midtrans_order_id, snap_token, created_at, updated_at, paid_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.MidtransOrderID,
		&i.SnapToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
	)
	return i, err
}

const getOrderByMidtransID = `-- name: GetOrderByMidtransID :one
SELECT id, user_id, status, total_amount, midtrans_order_id, snap_token, created_at, updated_at, paid_at
FROM orders
WHERE midtrans_order_id = $1
`

func (q *Queries) GetOrderByMidtransID(ctx context.Context, midtransOrderID pgtype.Text) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByMidtransID, midtransOrderID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.MidtransOrderID,
		&i.SnapToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
	)
	return i, err
}

const listExpiredPendingOrders = `-- name: ListExpiredPendingOrders :many
SELECT id, user_id, status, total_amount, midtrans_order_id, snap_token, created_at, updated_at, paid_at
FROM orders
WHERE status = 'pending_payment'
    AND created_at < $1
`

func (q *Queries) ListExpiredPendingOrders(ctx context.Context, createdAt pgtype.Timestamptz) ([]Order, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingOrders, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalAmount,
			&i.MidtransOrderID,
			&i.SnapToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, status, total_amount, midtrans_order_id, snap_token, created_at, updated_at, paid_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByUser(ctx context.Context, userID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalAmount,
			&i.MidtransOrderID,
			&i.SnapToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrderPaymentInfo = `-- name: SetOrderPaymentInfo :one
UPDATE orders
SET midtrans_order_id = $1,
    snap_token = $2,
    updated_at = now()
WHERE id = $3
RETURNING id, user_id, status, total_amount, midtrans_order_id, snap_token, created_at, updated_at, paid_at
`

type SetOrderPaymentInfoParams struct {
	MidtransOrderID pgtype.Text
	SnapToken       pgtype.Text
	ID              pgtype.UUID
}

func (q *Queries) SetOrderPaymentInfo(ctx context.Context, arg SetOrderPaymentInfoParams) (Order, error) {
	row := q.db.QueryRow(ctx, setOrderPaymentInfo, arg.MidtransOrderID, arg.SnapToken, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.MidtransOrderID,
		&i.SnapToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $1,
    paid_at = $2,
    updated_at = now()
WHERE id = $3
RETURNING id, user_id, status, total_amount, midtrans_order_id, snap_token, created_at, updated_at, paid_at
`

type UpdateOrderStatusParams struct {
	Status string
	PaidAt pgtype.Timestamptz
	ID     pgtype.UUID
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.Status, arg.PaidAt, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.MidtransOrderID,
		&i.SnapToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PaidAt,
	)
	return i, err
}
