// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_items.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, product_name, price, quantity, subtotal)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, product_id, product_name, price, quantity, subtotal, created_at
`

type CreateOrderItemParams struct {
	OrderID     pgtype.UUID
	ProductID   pgtype.UUID
	ProductName string
	Price       pgtype.Numeric
	Quantity    int32
	Subtotal    pgtype.Numeric
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.ProductName,
		arg.Price,
		arg.Quantity,
		arg.Subtotal,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductName,
		&i.Price,
		&i.Quantity,
		&i.Subtotal,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderItemsByOrder = `-- name: ListOrderItemsByOrder :many
SELECT id, order_id, product_id, product_name, price, quantity, subtotal, created_at
FROM order_items
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOrderItemsByOrder(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductName,
			&i.Price,
			&i.Quantity,
			&i.Subtotal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
