// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountProducts = `-- name: AdminCountProducts :one
SELECT COUNT(*)
FROM products
WHERE (
        $1::text IS NULL
        OR name ILIKE '%' || $1::text || '%'
    )
    AND (
        $2::text IS NULL
        OR category = $2::text
    )
`

type AdminCountProductsParams struct {
	Search   pgtype.Text
	Category pgtype.Text
}

func (q *Queries) AdminCountProducts(ctx context.Context, arg AdminCountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountProducts, arg.Search, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminGetDistinctCategories = `-- name: AdminGetDistinctCategories :many
SELECT DISTINCT category
FROM products
ORDER BY category
`

func (q *Queries) AdminGetDistinctCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, adminGetDistinctCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetProductByID = `-- name: AdminGetProductByID :one
SELECT id, name, description, price, stock, sku, category, is_active, created_at, updated_at, image_url
FROM products
WHERE id = $1
`

func (q *Queries) AdminGetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, adminGetProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Sku,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const adminGetProductBySKU = `-- name: AdminGetProductBySKU :one
SELECT id, name, description, price, stock, sku, category, is_active, created_at, updated_at, image_url
FROM products
WHERE sku = $1
`

func (q *Queries) AdminGetProductBySKU(ctx context.Context, sku string) (Product, error) {
	row := q.db.QueryRow(ctx, adminGetProductBySKU, sku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Sku,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const adminListProducts = `-- name: AdminListProducts :many
SELECT id, name, description, price, stock, sku, category, is_active, created_at, updated_at, image_url
FROM products
WHERE (
        $3::text IS NULL
        OR name ILIKE '%' || $3::text || '%'
    )
    AND (
        $4::text IS NULL
        OR category = $4::text
    )
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type AdminListProductsParams struct {
	Limit    int32
	Offset   int32
	Search   pgtype.Text
	Category pgtype.Text
}

func (q *Queries) AdminListProducts(ctx context.Context, arg AdminListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, adminListProducts,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.Sku,
			&i.Category,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*)
FROM products
WHERE is_active = true
    AND (
        $1::text IS NULL
        OR name ILIKE '%' || $1::text || '%'
    )
    AND (
        $2::text IS NULL
        OR category = $2::text
    )
`

type CountProductsParams struct {
	Search   pgtype.Text
	Category pgtype.Text
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.Search, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
        name,
        description,
        price,
        stock,
        sku,
        category,
        image_url
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, description, price, stock, sku, category, is_active, created_at, updated_at, image_url
`

type CreateProductParams struct {
	Name        string
	Description pgtype.Text
	Price       pgtype.Numeric
	Stock       int32
	Sku         string
	Category    string
	ImageUrl    pgtype.Text
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.Sku,
		arg.Category,
		arg.ImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Sku,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const getDistinctCategories = `-- name: GetDistinctCategories :many
SELECT DISTINCT category
FROM products
WHERE is_active = true
ORDER BY category
`

func (q *Queries) GetDistinctCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, price, stock, sku, category, is_active, created_at, updated_at, image_url
FROM products
WHERE id = $1
    AND is_active = true
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Sku,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, price, stock, sku, category, is_active, created_at, updated_at, image_url
FROM products
WHERE is_active = true
    AND (
        $3::text IS NULL
        OR name ILIKE '%' || $3::text || '%'
    )
    AND (
        $4::text IS NULL
        OR category = $4::text
    )
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit    int32
	Offset   int32
	Search   pgtype.Text
	Category pgtype.Text
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.Sku,
			&i.Category,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :one
UPDATE products
SET is_active = false
WHERE id = $1
RETURNING id, name, description, price, stock, sku, category, is_active, created_at, updated_at, image_url
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, softDeleteProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Sku,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $1,
    description = $2,
    price = $3,
    stock = $4,
    category = $5,
    is_active = $6,
    image_url = $7,
    updated_at = now()
WHERE id = $8
RETURNING id, name, description, price, stock, sku, category, is_active, created_at, updated_at, image_url
`

type UpdateProductParams struct {
	Name        string
	Description pgtype.Text
	Price       pgtype.Numeric
	Stock       int32
	Category    string
	IsActive    bool
	ImageUrl    pgtype.Text
	ID          pgtype.UUID
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.Category,
		arg.IsActive,
		arg.ImageUrl,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Sku,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}
